namespace WalletConnectSharp.Common.Model.Errors
{
    /// <summary>
    /// The ErrorType is an enum of error codes defined by
    /// their name
    /// </summary>
    public enum ErrorType : uint
    {
        // 0 (Generic)
        GENERIC = 0,
        
        // 10 (Internal)
        NON_CONFORMING_NAMESPACES = 9,

        // 1000 (Internal)
        MISSING_OR_INVALID = 1000,
        MISSING_RESPONSE = 1001,
        MISSING_DECRYPT_PARAMS = 1002,
        INVALID_UPDATE_REQUEST = 1003,
        INVALID_UPGRADE_REQUEST = 1004,
        INVALID_EXTEND_REQUEST = 1005,
        INVALID_STORAGE_KEY_NAME = 1020,
        RECORD_ALREADY_EXISTS = 1100,
        RESTORE_WILL_OVERRIDE = 1200,
        NO_MATCHING_ID = 1300,
        NO_MATCHING_TOPIC = 1301,
        NO_MATCHING_RESPONSE = 1302,
        NO_MATCHING_KEY = 1303,
        UNKNOWN_JSONRPC_METHOD = 1400,
        MISMATCHED_TOPIC = 1500,
        MISMATCHED_ACCOUNTS = 1501,
        SETTLED = 1600,
        NOT_APPROVED = 1601,
        PROPOSAL_RESPONDED = 1602,
        RESPONSE_ACKNOWLEDGED = 1603,
        EXPIRED = 1604,
        DELETED = 1605,
        RESUBSCRIBED = 1606,
        NOT_INITIALIZED = 1607,

        // 2000 (Timeout)
        SETTLE_TIMEOUT = 2000,
        JSONRPC_REQUEST_TIMEOUT = 2001,

        // 3000 (Unauthorized)
        UNAUTHORIZED_TARGET_CHAIN = 3000,
        UNAUTHORIZED_JSON_RPC_METHOD = 3001,
        UNAUTHORIZED_NOTIFICATION_TYPE = 3002,
        UNAUTHORIZED_UPDATE_REQUEST = 3003,
        UNAUTHORIZED_UPGRADE_REQUEST = 3004,
        UNAUTHORIZED_EXTEND_REQUEST = 3005,
        UNAUTHORIZED_MATCHING_CONTROLLER = 3100,
        UNAUTHORIZED_METHOD = 3101,

        // 4000 (EIP-1193)
        JSONRPC_REQUEST_METHOD_REJECTED = 4001,
        JSONRPC_REQUEST_METHOD_UNAUTHORIZED = 4100,
        JSONRPC_REQUEST_METHOD_UNSUPPORTED = 4200,
        DISCONNECTED_ALL_CHAINS = 4900,
        DISCONNECTED_TARGET_CHAIN = 4901,

        // 5000 (CAIP-25)
        DISAPPROVED_CHAINS = 5000,
        DISAPPROVED_JSONRPC = 5001,
        DISAPPROVED_NOTIFICATION = 5002,
        UNSUPPORTED_CHAINS = 5100,
        UNSUPPORTED_JSONRPC = 5101,
        UNSUPPORTED_NOTIFICATION = 5102,
        UNSUPPORTED_ACCOUNTS = 5103,
        USER_DISCONNECTED = 5900,

        // 9000 (Unknown)
        UNKNOWN = 9000,
    }
}